import Head from 'next/head';
import Image from 'next/image';
import Header from './Header';

export default function BaseLayout ({children}) {
    return <div className={''}>
    <Head>
      <title>Sampingan</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header/>
    <main className={'flex flex-column justify-center items-center min-h-screen min-w-fit'}>
      {children}
    </main>

    <footer className={''}>
      
    </footer>
  </div>
}