import Head from 'next/head';


export default function LoginLayout ({children, title="Login Sampingan"}) {
    return <div className={''}>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={'bg-gray-800 flex flex-column justify-center items-center min-h-screen min-w-fit'}>
      {children}
    </main>

    <footer className={''}>
      
    </footer>
  </div>
}